### GENERAL SETTINGS ###

# Site settings
title: "YANTRIX"
description: "This is portfolio of YANTRIX the official technical club of PUSSGRC,HOSHIARPUR, developed by Platform. It sharpen the  technical skills of college students."
analytics: UA-104964578-1
baseurl:   ""
url: "https://pussgrc.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/pussgrc/
  - title: facebook
    url: https://www.facebook.com/yantrixUIETH/
  - title: twitter
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - PUSSGRC, UNA ROAD, BAJWARA.
    -     HOSHIARPUR, 146023
    -         PUNJAB,INDIA.
email: "support@platform.net.in"
tel: "(+91)9631560280"


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: DILIP KUMAR SHARMA
    position: CORE MEMBER
    text: FULL-STACK WEB DEVELOPER, IOT MAANAGER.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:krdilip276@gmail.com
      - title: facebook
        url: https://www.facebook.com/dilipkumar.sharma.7731247
      - title: github
        url: https://github.com/dilip-cse
      - title: linkedin
        url: https://in.linkedin.com/in/dilip-kumar-sharma-a837b2134
  - name: CHETAN MALHOTRA
    position: CORE MEMBER
    text: MICROCONTROLLER, MICROPROCESSOR
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:chetanbhusanmalhotra@gmail.com
      - title: facebook
        url: https://www.facebook.com/chetanmalhotra1388
  - name: Ayush raj
    position: CORE MEMBER
    text: HARDWARE PROGRAMMING, OPERATING SYSTEM
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:araj5ak@gmail.com
      - title: facebook
        url: https://www.facebook.com/araj5ak
# Clients information. Shown on Home and About pages.
clients:
  - name: platform.net.in
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "NGO-INCUBATOR is a platform that provides collaborating oppurtunities and helping hand."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Building technical systems involves a lot of hard work and specialized knowledge: languages and protocols, coding and debugging, testing and refactoring."
    author: "YANTRIX"
    position: Technical club
